// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/item/type.go
//
// Generated by this command:
//
//	mockgen -source=app/domain/item/type.go -destination=mocks/domain/item/function.go
//

// Package mock_item is a generated GoMock package.
package mock_item

import (
	reflect "reflect"

	model "github.com/inventory-service/model"
	error_wrapper "github.com/inventory-service/lib/error_wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockItemDomain is a mock of ItemDomain interface.
type MockItemDomain struct {
	ctrl     *gomock.Controller
	recorder *MockItemDomainMockRecorder
	isgomock struct{}
}

// MockItemDomainMockRecorder is the mock recorder for MockItemDomain.
type MockItemDomainMockRecorder struct {
	mock *MockItemDomain
}

// NewMockItemDomain creates a new mock instance.
func NewMockItemDomain(ctrl *gomock.Controller) *MockItemDomain {
	mock := &MockItemDomain{ctrl: ctrl}
	mock.recorder = &MockItemDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemDomain) EXPECT() *MockItemDomainMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockItemDomain) Create(name, supplierID, category, unit string, price, portionSize float64) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, supplierID, category, unit, price, portionSize)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockItemDomainMockRecorder) Create(name, supplierID, category, unit, price, portionSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockItemDomain)(nil).Create), name, supplierID, category, unit, price, portionSize)
}

// Delete mocks base method.
func (m *MockItemDomain) Delete(id string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockItemDomainMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockItemDomain)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockItemDomain) FindAll() ([]model.Item, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockItemDomainMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockItemDomain)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockItemDomain) FindByID(id string) (*model.Item, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Item)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockItemDomainMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockItemDomain)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockItemDomain) Update(id, supplierID, name, category string, price float64, unit string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, supplierID, name, category, price, unit)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockItemDomainMockRecorder) Update(id, supplierID, name, category, price, unit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockItemDomain)(nil).Update), id, supplierID, name, category, price, unit)
}
