// Code generated by MockGen. DO NOT EDIT.
// Source: internal/resource/branch/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/resource/branch/type.go -destination=mocks/resource/branch/function.go
//

// Package mock_branch is a generated GoMock package.
package mock_branch

import (
	reflect "reflect"

	model "github.com/inventory-service/app/model"
	error_wrapper "github.com/inventory-service/lib/error_wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockBranchResource is a mock of BranchResource interface.
type MockBranchResource struct {
	ctrl     *gomock.Controller
	recorder *MockBranchResourceMockRecorder
	isgomock struct{}
}

// MockBranchResourceMockRecorder is the mock recorder for MockBranchResource.
type MockBranchResourceMockRecorder struct {
	mock *MockBranchResource
}

// NewMockBranchResource creates a new mock instance.
func NewMockBranchResource(ctrl *gomock.Controller) *MockBranchResource {
	mock := &MockBranchResource{ctrl: ctrl}
	mock.recorder = &MockBranchResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranchResource) EXPECT() *MockBranchResourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBranchResource) Create(name, location, branchManagerId string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, location, branchManagerId)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBranchResourceMockRecorder) Create(name, location, branchManagerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBranchResource)(nil).Create), name, location, branchManagerId)
}

// Delete mocks base method.
func (m *MockBranchResource) Delete(id string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBranchResourceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBranchResource)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockBranchResource) FindAll() ([]model.Branch, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Branch)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBranchResourceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBranchResource)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockBranchResource) FindByID(id string) (*model.Branch, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Branch)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBranchResourceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBranchResource)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockBranchResource) Update(id, name, location, branchManagerId string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, name, location, branchManagerId)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBranchResourceMockRecorder) Update(id, name, location, branchManagerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBranchResource)(nil).Update), id, name, location, branchManagerId)
}
