// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/purchase/type.go
//
// Generated by this command:
//
//	mockgen -source=app/domain/purchase/type.go -destination=mocks/domain/purchase/functiong.o
//

// Package mock_purchase is a generated GoMock package.
package mock_purchase

import (
	reflect "reflect"

	model "github.com/inventory-service/model"
	error_wrapper "github.com/inventory-service/lib/error_wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseDomain is a mock of PurchaseDomain interface.
type MockPurchaseDomain struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseDomainMockRecorder
	isgomock struct{}
}

// MockPurchaseDomainMockRecorder is the mock recorder for MockPurchaseDomain.
type MockPurchaseDomainMockRecorder struct {
	mock *MockPurchaseDomain
}

// NewMockPurchaseDomain creates a new mock instance.
func NewMockPurchaseDomain(ctrl *gomock.Controller) *MockPurchaseDomain {
	mock := &MockPurchaseDomain{ctrl: ctrl}
	mock.recorder = &MockPurchaseDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseDomain) EXPECT() *MockPurchaseDomainMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPurchaseDomain) Create(supplierId, branchId, itemId string, quantity int, purchaseCost float64) (*model.Purchase, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", supplierId, branchId, itemId, quantity, purchaseCost)
	ret0, _ := ret[0].(*model.Purchase)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPurchaseDomainMockRecorder) Create(supplierId, branchId, itemId, quantity, purchaseCost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPurchaseDomain)(nil).Create), supplierId, branchId, itemId, quantity, purchaseCost)
}

// Delete mocks base method.
func (m *MockPurchaseDomain) Delete(id string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPurchaseDomainMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPurchaseDomain)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockPurchaseDomain) FindAll() ([]model.Purchase, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Purchase)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPurchaseDomainMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPurchaseDomain)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockPurchaseDomain) FindByID(id string) (*model.Purchase, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Purchase)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPurchaseDomainMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPurchaseDomain)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockPurchaseDomain) Update(id, supplierId, branchId, itemId string, quantity int, purchaseCost float64) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, supplierId, branchId, itemId, quantity, purchaseCost)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPurchaseDomainMockRecorder) Update(id, supplierId, branchId, itemId, quantity, purchaseCost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPurchaseDomain)(nil).Update), id, supplierId, branchId, itemId, quantity, purchaseCost)
}
