// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/branch/type.go
//
// Generated by this command:
//
//	mockgen -source=app/domain/branch/type.go -destination=mocks/domain/branch/function.go
//

// Package mock_branch is a generated GoMock package.
package mock_branch

import (
	reflect "reflect"

	model "github.com/inventory-service/model"
	error_wrapper "github.com/inventory-service/lib/error_wrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockBranchDomain is a mock of BranchDomain interface.
type MockBranchDomain struct {
	ctrl     *gomock.Controller
	recorder *MockBranchDomainMockRecorder
	isgomock struct{}
}

// MockBranchDomainMockRecorder is the mock recorder for MockBranchDomain.
type MockBranchDomainMockRecorder struct {
	mock *MockBranchDomain
}

// NewMockBranchDomain creates a new mock instance.
func NewMockBranchDomain(ctrl *gomock.Controller) *MockBranchDomain {
	mock := &MockBranchDomain{ctrl: ctrl}
	mock.recorder = &MockBranchDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranchDomain) EXPECT() *MockBranchDomainMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBranchDomain) Create(name, location, branchManagerId string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, location, branchManagerId)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBranchDomainMockRecorder) Create(name, location, branchManagerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBranchDomain)(nil).Create), name, location, branchManagerId)
}

// Delete mocks base method.
func (m *MockBranchDomain) Delete(id string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBranchDomainMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBranchDomain)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockBranchDomain) FindAll() ([]model.Branch, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Branch)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBranchDomainMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBranchDomain)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockBranchDomain) FindByID(id string) (*model.Branch, *error_wrapper.ErrorWrapper) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Branch)
	ret1, _ := ret[1].(*error_wrapper.ErrorWrapper)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBranchDomainMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBranchDomain)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockBranchDomain) Update(id, name, location, branchManagerId string) *error_wrapper.ErrorWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, name, location, branchManagerId)
	ret0, _ := ret[0].(*error_wrapper.ErrorWrapper)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBranchDomainMockRecorder) Update(id, name, location, branchManagerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBranchDomain)(nil).Update), id, name, location, branchManagerId)
}
